apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-site
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: meu-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: production
